eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8701/eureka/
server:
  port: 8714
feign:
  hystrix:
    enabled: true
spring:
  zipkin:
    #服务端地址
    base-url: http://127.0.0.1:9990
    #本项目服务名
    service:
      name: ${spring.application.name}
  sleuth:
    #监控开关
    enabled: true
    #采样率
    sampler:
      percentage: 1