eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8701/eureka/
server:
  port: 8714
feign:
  hystrix:
    enabled: true
spring:
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    enabled: true
    baseUrl: http://127.0.0.1:9990