eureka:
  healthcheck:
    enabled: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8701/eureka/
server:
  port: 8711
spring:
  zipkin:
    base-url: http://127.0.0.1:9990
    service:
      name: ${spring.application.name}
  sleuth:
    enabled: true
    sampler:
      percentage: 1